'use strict';

const TCF_DATA = {
  nodes: [
    {
      id: 'tcf',
      label: 'TCF',
      fullName: 'Transnational Community Federation e.V.',
      category: 'community',
      status: 'Active',
      size: 52,
      tagline: 'Building democratic infrastructure for Iran',
      description:
        'TCF (Transnational Community Federation e.V.) is a German-registered civil society organization and the home of all these projects. We build the digital and civic infrastructure for Iranian democratic participation — from ZK-based identity and voting to deliberation platforms, civic education, and civil society mapping.',
      links: [{ label: 'transcf.org', url: 'https://transcf.org' }],
      color: '#F9C452',
    },
    {
      id: 'dfii',
      label: 'DFII',
      fullName: 'Democratization Framework for an Inclusive Iran',
      category: 'framework',
      status: 'Active',
      size: 36,
      tagline: 'Partnership consortium for democratic transition',
      description:
        'DFII (Democratization Framework for an Inclusive Iran) is a multi-organization partnership consortium for democratic transition. TCF participates in DFII as the digital infrastructure provider — Jomhoor serves as the civic tech backbone of the broader framework, enabling verifiable identity and participation across partner organizations.',
      links: [],
      color: '#5B9DF5',
    },
    {
      id: 'jomhoor',
      label: 'Jomhoor',
      fullName: 'Digital Democracy Platform',
      category: 'infrastructure',
      status: 'Active',
      size: 44,
      tagline: 'Privacy-first identity & civic infrastructure',
      description:
        'Jomhoor ("Republic" in Persian) is a privacy-preserving digital democracy platform. Using NFC document scanning and zero-knowledge proofs on Rarimo L2, it enables Iranians to prove their identity and participate in democratic processes without revealing personal data. The platform encompasses a mobile wallet, voting infrastructure, deliberation tools, and SSO.',
      links: [
        { label: 'jomhoor.org', url: 'https://jomhoor.org' },
        { label: 'iranians.vote', url: 'https://iranians.vote' },
      ],
      color: '#5B9DF5',
    },
    {
      id: 'wallet',
      label: 'Jomhoor Wallet',
      fullName: 'Jomhoor Mobile Wallet App',
      category: 'infrastructure',
      status: 'Active',
      size: 28,
      tagline: 'Your sovereign identity in your pocket',
      description:
        'A React Native (Expo SDK 52) mobile application that scans your passport or Iranian National ID via NFC, generates zero-knowledge proofs entirely on-device, and lets you vote in referendums — without biometric data ever leaving your phone. Built on Rarimo L2 for transparent, tamper-proof records.',
      links: [],
      color: '#38BDF8',
    },
    {
      id: 'sso',
      label: 'Jomhoor SSO',
      fullName: 'Sign in with Jomhoor',
      category: 'infrastructure',
      status: 'Active',
      size: 24,
      tagline: 'OAuth2 identity bridge for civic apps',
      description:
        "A wallet-based OAuth2 SSO system (auth-code + PKCE) with mandatory App Attest (iOS) and Play Integrity (Android) verification. Relying parties receive pairwise pseudonymous subjects — your wallet address is never exposed. Powers authentication across Taraaz, Civic Compass, and partner platforms.",
      links: [{ label: 'sso.jomhoor.org', url: 'https://sso.jomhoor.org' }],
      color: '#38BDF8',
    },
    {
      id: 'iranians-vote',
      label: 'Iranians.Vote',
      fullName: 'ZK Referendum Platform',
      category: 'democracy',
      status: 'Active',
      size: 36,
      tagline: 'Anonymous, verifiable blockchain voting',
      description:
        'A referendum platform where Iranians cast votes on critical questions, with results recorded immutably on the Rarimo L2 blockchain. Zero-knowledge proofs guarantee each person votes only once while keeping ballots completely anonymous. Supports both Iranian passports and National ID (INID) cards.',
      links: [{ label: 'iranians.vote', url: 'https://iranians.vote' }],
      color: '#AC95DC',
    },
    {
      id: 'taraaz',
      label: 'Taraaz',
      fullName: 'Civic Deliberation Platform',
      category: 'democracy',
      status: 'Active',
      size: 30,
      tagline: 'Structured civic dialogue at scale',
      description:
        "Taraaz is a deliberation platform forked from Agora (zkorum), adapted for the Iranian diaspora. It enables structured, nuanced civic conversations that surface both agreement and disagreement across the community — going far beyond simple yes/no votes to build genuine democratic consensus.",
      links: [],
      color: '#AC95DC',
    },
    {
      id: 'compass',
      label: 'Civic Compass',
      fullName: 'Political Identity Mapper',
      category: 'democracy',
      status: 'Active',
      size: 28,
      tagline: 'Explore your political identity across 8 dimensions',
      description:
        'Civic Compass helps Iranians articulate and explore their political values across eight key dimensions — from economic policy to governance structures to civil liberties. By mapping diversity within the movement, it helps build bridges, find common ground, and clarify what a future Iran might look like.',
      links: [{ label: 'compass.jomhoor.org', url: 'https://compass.jomhoor.org' }],
      color: '#AC95DC',
    },
    {
      id: 'atlas',
      label: 'Atlas Iran',
      fullName: 'Atlas of Iranian Diasporic Civil Society',
      category: 'community',
      status: 'Active',
      size: 32,
      tagline: 'Mapping the Iranian civil society network',
      description:
        'Atlas Iran systematically maps and analyzes the network of Iranian civil society organizations in the diaspora. By charting relationships, resources, and capability gaps, it gives the movement unprecedented visibility into its own structure — enabling smarter coordination and coalition-building for democratic change.',
      links: [{ label: 'atlasiran.org', url: 'https://atlasiran.org' }],
      color: '#F9C452',
    },
    {
      id: 'university',
      label: 'University in Exile',
      fullName: 'University in Exile',
      category: 'knowledge',
      status: 'Active',
      size: 26,
      tagline: 'Academic sanctuary for Iranian scholars',
      description:
        "University in Exile provides academic refuge and educational programs for Iranian scholars and students displaced by the regime. It maintains academic continuity across generations, preserves institutional knowledge, and cultivates the human capacity that a democratic Iran will need to govern itself.",
      links: [{ label: 'transcf.org', url: 'https://transcf.org/university-in-exile' }],
      color: '#0EBB90',
    },
    {
      id: 'inid',
      label: 'INID SDK',
      fullName: 'Iranian National ID Open SDK',
      category: 'infrastructure',
      status: 'Active',
      size: 24,
      tagline: 'Open-source NFC reader for Iranian IDs',
      description:
        "An open-source SDK that reverse-engineers the Iranian National ID (INID) card protocol, enabling NFC reading and cryptographic verification of Iranian identities without relying on the Iranian government's infrastructure. A critical building block for privacy-preserving identity verification at scale.",
      links: [{ label: 'GitHub', url: 'https://github.com/Iranians-Vote-Digital-Democracy/INIDOSDK' }],
      color: '#38BDF8',
    },
    {
      id: 'difcongress',
      label: 'DIF Congress',
      fullName: 'Digital Iran Freedom Congress',
      category: 'democracy',
      status: 'Active',
      size: 28,
      tagline: 'Multi-lingual public platform for democratic transition',
      description:
        'The Digital Iran Freedom Congress (DIFC) is a public-facing multi-lingual site (Persian, Kurdish, Arabic, Balochi, Azeri, English) serving as a civic hub for the Iranian freedom movement. It integrates Jomhoor SSO for participant authentication, allowing verified Iranian citizens to participate in congress activities while protecting their identity.',
      links: [{ label: 'difcongress.com', url: 'https://difcongress.com' }],
      color: '#AC95DC',
    },
  ],

  links: [
    { source: 'tcf',  target: 'dfii',          strength: 0.8 },
    { source: 'tcf',  target: 'jomhoor',        strength: 1.0 },
    { source: 'tcf',  target: 'atlas',          strength: 0.8 },
    { source: 'tcf',  target: 'university',     strength: 0.7 },
    { source: 'jomhoor', target: 'dfii',        strength: 0.7 },
    { source: 'jomhoor', target: 'wallet',       strength: 1.0 },
    { source: 'jomhoor', target: 'iranians-vote', strength: 0.9 },
    { source: 'jomhoor', target: 'taraaz',        strength: 0.8 },
    { source: 'jomhoor', target: 'compass',       strength: 0.8 },
    { source: 'jomhoor', target: 'sso',           strength: 0.9 },
    { source: 'jomhoor', target: 'inid',          strength: 0.9 },
    { source: 'sso', target: 'taraaz',         strength: 0.7 },
    { source: 'sso', target: 'compass',        strength: 0.7 },
    { source: 'sso', target: 'difcongress',    strength: 0.8 },
    { source: 'inid', target: 'iranians-vote', strength: 0.7 },
    { source: 'wallet', target: 'iranians-vote', strength: 0.8 },
  ],
};
